[Server]
Debug = false
Host = "127.0.0.1"
Port = 8001
ReadTimeout = 300 # 读取请求的超时时间
WriteTimeout = 300 # 写入响应的超时时间
IdleTimeout = 300 # keep-alive 超时时间

[Log]
Level = "DEBUG"
Path = "./log/all.log"
Db = "./log/gorm.log"
Err = "./log/err.log"

[Db]
Enable = false
Type = "pgsql"
DSN = "host=127.0.0.1 port=5432 user=postgres dbname=postgres sslmode=disable TimeZone=Asia/Shanghai"
DbLog = "./log/gorm.log"
MaxLifetime = 3600 # 设置连接可以重用的最长时间(单位：秒)
MaxIdletime = 600 # 设置连接可以重用的最长时间(单位：秒)
MaxOpenConns = 100 # 设置数据库的最大打开连接数
MaxIdleConns = 30 # 设置空闲连接池中的最大连接数
SlowThreshold = 3

[Jwt]
JwtTokenSignKey = "我是jwt 秘钥" # 设置token生成时加密的签名
ExpiresTime = "48h" # 设置token过期时间，最大支持h

[Websocket]
Start = 0 # 默认不启动该服务（1=启动；0=不启动）
WriteReadBufferSize = 20480 # 读写缓冲区分配字节，大概能存储 6800 多一点的文字
MaxMessageSize = 65535 # 从消息管道读取消息的最大字节
PingPeriod = 20 # 心跳包频率，单位：秒
HeartbeatFailMaxTimes = 4 # 允许心跳失败的最大次数
ReadDeadline = 100 # 客户端在线情况下，正常的业务消息间隔秒数必须小于该值，否则服务器将会主动断开
WriteDeadline = 35 # 消息单次写入超时时间，单位：秒

[Redis]
Host = "localhost"
Port = 6379
Password = ""
Db = 0
MaxIdle = 10
MaxActive = 100
IdleTimeout = 300
PoolSize = 100
MinIdleConns = 5

[Mail]
Host = "smtp.qq.com"
Port = 465
Username = ""
Password = ""